---
- name: Configure | Create a service account
  user:
    name: "{{ kibana_user }}"

- name: Configure | Ensure base folder structure
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0777
  with_items:
    - "{{ base_dir }}"
    - "{{ cfgs_dir }}"

- name: Configure | Create releases folder
  file:
    path: "{{ base_dir }}/releases"
    state: directory
    owner: "{{ kibana_user }}"
    group: "{{ kibana_group }}"
    mode: 0777

- name: Configure | Create systemd file
  template:
    src: kibana.service.j2
    dest: "{{ systemd_file_path }}/kibana.service"
    owner: root
    group: "{{ kibana_group }}"
  no_log: no
  notify: restart kibana

- name: Configure | Get configs for ELK
  git:
    repo: "{{ cfgs_repo }}"
    dest: "{{ cfgs_dir }}"
    force: yes
  tags:
    - skip_ansible_lint
